name: grounding_zones
channels:
  - conda-forge
dependencies:
  - cartopy
  - earthengine-api
  - gdal
  - h5py>=2.9=mpi*
  - lxml
  - matplotlib
  - mpi4py
  - netCDF4
  - notebook
  - numpy
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - scikit-learn
  - shapely
  - pip:
     - ATM1b-QFIT
     - geoid-toolkit
     - icesat2-toolkit
     - pyTMD
     - spatial-interpolators
